[2024-11-29 16:12:48,971] 21 root - INFO - Data Ingestion has been started
[2024-11-29 16:12:48,971] 23 root - INFO - Data reading using Pandas from local file system
[2024-11-29 16:12:48,996] 25 root - INFO - Data Reading has been completed
[2024-11-29 16:12:49,132] 29 root - INFO - Raw data has been stored
[2024-11-29 16:12:49,139] 32 root - INFO - Raw data has been splitted into Train and Test set
[2024-11-29 16:12:49,267] 37 root - INFO - Data Ingestion has been completed!
[2024-11-29 16:12:49,269] 52 root - INFO - Created feature store configuration at /home/lutful/Modular-Workflow-and-project-setup/feature_repo/feature_story.yaml
[2024-11-29 16:12:49,269] 56 root - INFO - Configuration file content: 
 
            Project: income_prediction 
            provider:local
            registry:data/registry.db
            online_store:
                type:sqlite
            offline_store:
                type:file
            entity_key_serialization_version:2
            
[2024-11-29 16:12:49,270] 63 root - ERROR - Error in initialization:[Errno 2] No such file or directory: '/home/lutful/Modular-Workflow-and-project-setup/feature_repo/feature_store.yaml'
[2024-11-29 16:12:49,270] 49 root - ERROR - 
→Error occured in Python script:
→File: /home/lutful/Modular-Workflow-and-project-setup/src/components/data_transformation.py
→Line number:59
→Error message: [Errno 2] No such file or directory: '/home/lutful/Modular-Workflow-and-project-setup/feature_repo/feature_store.yaml'
