[2024-11-29 16:10:24,230] 21 root - INFO - Data Ingestion has been started
[2024-11-29 16:10:24,230] 23 root - INFO - Data reading using Pandas from local file system
[2024-11-29 16:10:24,269] 25 root - INFO - Data Reading has been completed
[2024-11-29 16:10:24,396] 29 root - INFO - Raw data has been stored
[2024-11-29 16:10:24,402] 32 root - INFO - Raw data has been splitted into Train and Test set
[2024-11-29 16:10:24,533] 37 root - INFO - Data Ingestion has been completed!
[2024-11-29 16:10:24,534] 63 root - ERROR - Error in initialization:expected str, bytes or os.PathLike object, not DataTransformationConfig
[2024-11-29 16:10:24,534] 49 root - ERROR - 
→Error occured in Python script:
→File: /home/lutful/Modular-Workflow-and-project-setup/src/components/data_transformation.py
→Line number:31
→Error message: expected str, bytes or os.PathLike object, not DataTransformationConfig
